import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar, { HeaderImg } from './navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'RAG',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <NavBar></NavBar>
          {/* <HeaderImg imagen='/img/bg1.jpg'/> */}
        </header>
        <main className='bg-black'>
          {children}
        </main>
      </body>
    </html>
  )
}
