import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import NavBar, { ImgNavBar } from './navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'RAG',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <nav>
            <NavBar></NavBar>
            {/* <ImgNavBar></ImgNavBar> */}
          </nav>
        </header>
        <main className='dark:bg-black min-h-screen'>
          {children}
        </main>
      </body>
    </html>
  )
}
